Android.mk
Makefile
libteec/Makefile
libteec/include/teec.h
libteec/src/tee_client_api.c
public/tee_client_api.h
tee-supplicant/Makefile
tee-supplicant/src/tee_supp_fs.c
tee-supplicant/src/tee_supplicant.c
tee-supplicant/src/teec_ta_load.c
tee-supplicant/src/teec_ta_load.h

Update of the client part, related to the Linux Driver
Refactoring at https://github.com/OP-TEE/optee_linuxdriver/pull/17
Fix #16
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

Updated related Linux Driver Refactoring

---

Android.mk
libteec/Makefile
libteec/include/linux/tee_ioc.h
tee-supplicant/Makefile

Remove dependency on optee_linuxdriver/include/tee_ioc.h

---

libteec/src/tee_client_api.c
public/tee_client_api.h

Align TEEC_FinalizeContext with GP specifications

---

libteec/include/linux/tee_ioc.h
libteec/src/tee_client_api.c
public/tee_client_api.h
tee-supplicant/src/tee_supp_fs.c

dma_buf support

---

tee-supplicant/src/tee_supp_fs.c

I started fixing a buffer overrun, but then I continued cleaning up a bit more.

Various fixes for tee-supplicant filesystem

---

Makefile

Remove unused ROOTFS installation

---

tee-supplicant/src/tee_supp_fs.c

This patch should work with the commit in optee_os:
a5c22091cd5aaee9a8da2d87f6937a46714e7a11
Signed-off-by: SY Chiu <sy.chiu@linaro.org>
Tested-by: SY Chiu <sy.chiu@linaro.org> (QEMU)

Storage: Added create hard-link operation

---

LICENSE
Notice.md

`Signed-off-by: Joakim Bech <joakim.bech@linaro.org>`

Changing from old STM CLA to the new DCO

---

tee-supplicant/src/tee_supplicant.c

Add mutex to protect global variable shared_memory_list

---

tee-supplicant/Makefile
tee-supplicant/src/hmac_sha2.c
tee-supplicant/src/hmac_sha2.h
tee-supplicant/src/rpmb.c
tee-supplicant/src/sha2.c
tee-supplicant/src/sha2.h

~~This PR is on top of https://github.com/OP-TEE/optee_client/pull/43, so please consider only the last commit, c74fbb2 ("RPMB: add HMAC to emulation mode").~~

RPMB emulation HMAC support

---

tee-supplicant/src/rpmb.c

Prior to this commit, the RPMB code was tested in emulation mode only
(RPMB_EMU=1). This fixes a couple of issues found when testing with a
real eMMC device on a HiKey board. The eMMC is a Hardkernel 8GB module
plugged into the microSD port. Kernel is from Linaro's 96boards
repository [1], slightly modified so that the RPMB can be used on the
microSD connector (MMC_CAP_CMD23 is added to the capability flags of
the second MMC controller).
[1] https://github.com/96boards/linux branch hikey commit 54e6524885a9
("Merge pull request #178 from xin3liang/hikey-3.18-720p-boot-issue").

RPMB: fix read_cid() and data access with a real eMMC device

---

libteec/src/tee_client_api.c

When the ioctl() call inside TEEC_OpenSession() or TEEC_InvokeCommand()
fails, TEEC_ERROR_BAD_STATE is returned. Update the error path to
return more descriptive codes:
- TEEC_ERROR_OUT_OF_MEMORY if ioctl() has set errno to ENOMEM (with the
current driver, this can occur when the driver's private memory pool is
full).
- TEEC_ERROR_GENERIC otherwise.

Adjust error codes for TEEC_OpenSession() and TEEC_InvokeCommand()

---

README.md

README: Update legacy toolchain download url

---

config.mk
libteec/include/linux/tee.h
tee-supplicant/Makefile
tee-supplicant/src/__tee_ipsocket.h
tee-supplicant/src/__tee_isocket_defines.h
tee-supplicant/src/__tee_tcpsocket_defines.h
tee-supplicant/src/__tee_tcpsocket_defines_extensions.h
tee-supplicant/src/__tee_udpsocket_defines.h
tee-supplicant/src/gprof.c
tee-supplicant/src/gprof.h
tee-supplicant/src/handle.c
tee-supplicant/src/handle.h
tee-supplicant/src/optee_msg_supplicant.h
tee-supplicant/src/rpmb.c
tee-supplicant/src/sql_fs.c
tee-supplicant/src/sql_fs.h
tee-supplicant/src/tee_socket.c
tee-supplicant/src/tee_socket.h
tee-supplicant/src/tee_supp_fs.c
tee-supplicant/src/tee_supp_fs.h
tee-supplicant/src/tee_supplicant.c
tee-supplicant/src/tee_supplicant.h

Depends on https://github.com/linaro-swg/linux/pull/30

Gp socket support

---

Makefile
libteec/Makefile

libteec/Makefile: generate static library (libteec.a)

---

tee-supplicant/src/tee_supplicant.c

subj
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

tee-supplicant: fix use of mem after it's freed

---

tee-supplicant/src/tee_supplicant.c

Add the missing code to make tee-supplicant a proper daemon when invoked
with -d.

tee-supplicant: add daemon mode (-d)

---

libteec/src/tee_client_api.c

Fix build warnings reported by the Buildroot team [1]:
/home/thomas/projets/outputs/armv5-ctng-linux-gnueabi/build/optee-client-3.4.0/libteec/src/tee_client_api.c: In function 'TEEC_InitializeContext':
/home/thomas/projets/outputs/armv5-ctng-linux-gnueabi/build/optee-client-3.4.0/libteec/src/tee_client_api.c:149:28: error: 'gen_caps' may be used uninitialized in this function [-Werror=maybe-uninitialized]
ctx->reg_mem = gen_caps & TEE_GEN_CAP_REG_MEM;
^
/home/thomas/projets/buildroot/output/build/optee-client-3.4.0/libteec/src/tee_client_api.c: In function ‘TEEC_OpenSession’:
/home/thomas/projets/buildroot/output/build/optee-client-3.4.0/libteec/src/tee_client_api.c:507:8: error: cast increases required alignment of target type [-Werror=cast-align]
arg = (struct tee_ioctl_open_session_arg …

libteec: fix build warnings

---

public/tee_client_api.h

tee_client_api: fix typo in comment

---

.travis.yml
scripts/checkpatch_inc.sh
typedefs.checkpatch

Adds checks with checkpatch on new patches.

travis: run checkpach on patches

---

libckteec/src/pkcs11_token.c

When caller of `C_GetSlotList()` provides a non-NULL buffer reference with a count value of zero, the TA gets invoked with a null buffer reference in the OP-TEE shared memory, hence it will return `CKR_OK` status since it legitimately only returns the count information.
This change makes ckteec library to return `CKR_BUFFER_TOO_SMALL` as per PKCS#11 specification.
This change also fixes `C_GetSlotList()` that, prior to this change, would have returned `CKR_ARGUMENTS_BAD` upon `NULL` buffer and non-zero count value whereas specification says:
> If pSlotList is NULL_PTR, (...). The contents of *pulCount on entry to C_GetSlotList has no meaning in this case (...).
Found the issue from https://github.com/OP-TEE/optee_os/pull/3644#discussion_r387592239.

libckteec: better handle null size buffer in C_GetSlotList()

---

libteec/src/tee_client_api.c

TEE Client API specification states that only with login methods
TEEC_LOGIN_GROUP and TEEC_LOGIN_GROUP_APPLICATION connection data is
non-NULL.
In current Linux kernel API interfece it is not possible to handle custom
connection data so every login method needs to be manually passed thru
clnt_uuid field and handled specially both in user space and in kernel to
allow kernel to do proper authorization checking when opening an session.
This is related to: https://github.com/OP-TEE/optee_os/issues/3642

libteec: Update TEEC_OpenSession() to pass connection data based on method

---

libckteec/include/pkcs11_ta.h
libckteec/src/pkcs11_api.c
libckteec/src/pkcs11_token.c
libckteec/src/pkcs11_token.h

Add support code for issuing C_SeedRandom() and C_GenerateRandom()
commands to TA.

libckteec: Add implementation for random number generation

---

libckteec/src/pkcs11_processing.c

Change all impacted processing function to release the active processing
when it returns an error or an error other than CKR_BUFFER_TOO_SMALL.

libckteec: release active processing on functions failures

---

libckteec/src/serialize_ck.c

Even thou CK_ULONG is known size some application might still ask the size
in generic way for all attributes.
CK_ULONG has additional twist -- in 64 bit targets user space is 64 bit
but TA interface handles that as 32 bit. This change handles both
transparently.
Related PRs:
- https://github.com/OP-TEE/optee_test/pull/525

libckteec: Fix querying size of CK_ULONG attributes

---

libckteec/src/pkcs11_processing.c
libckteec/src/serialize_ck.c

Few bug fixes in pkcs11 library

libckteec: Miscellaneus fixes

---

tee-supplicant/src/tee_socket.c

Updates tee_socket_recv() to detect and report truncated datagrams and
enable amount of data available to be queried.

tee-supplicant: tee_socket_recv(): report tructated datagrams

---

.github/workflows/stales.yml

Add a stales.yml similar to the ones we find in the other OP-TEE gits.
Signed-off-by: Joakim Bech <joakim.bech@linaro.org>

GitHub actions: add a stales.yml file

---

tee-supplicant/src/plugin.c

List of the plugins to be loaded by tee-supplicant is constructed based on the content of the `TEE_PLUGIN_LOAD_PATH` directory. However when plugins are loaded only file name is passed to the `dlopen()` function.
This means that actual plugin is loaded at first hit based on `LD_LIBRARY_PATH` search path.
This could result in loading of completely different file than actually intended.
Solution is to pass full file path to the `dlopen()`, that is `TEE_PLUGIN_LOAD_PATH` + plugin filename.

tee-supplicant: fix plugin loading logic

---

tee-supplicant/src/tee_supplicant.c

This commit addresses a race condition when a kernel module using OP-TEE
is loaded immediately after tee-supplicant is started. To understand the
problem, consider that with a shell background task there is no guarantee
that the service is available to the kernel when the command returns.
So the following:
tee-supplicant &
modprobe <some_module>
...may fail when <some_module> invokes the kernel TEE client API (note
that kernel users do NOT wait for the supplicant to be available [1],
contrary to user space clients [1]).
This scenario was addressed by commit 66cdd5db37db ("tee-supplicant: add
daemon mode (-d)"), although the commit description did not explicitly
mention it. With '-d ' the supplicant command would open the device
before returning. Unfortunately, this was inadvertently …

tee-supplicant: -d: return after TEE device is opened

---

tee-supplicant/src/rpmb.c

For now tee-supplicant retrieve rpmb informations by opening mmc dev node and read data at the corresponding offset.
That is a problem on Android device with selinux enabled because the access to this node is restricted to kernel/init.
All the necessary informations can instead be read from sysfs:
- RPMB partition size:
/sys/class/mmc_host/mmc%u/mmc%u:0001/raw_rpmb_size_mult
- Reliable write sector count:
/sys/class/mmc_host/mmc%u/mmc%u:0001/rel_sectors

tee-supplicant: read rpmb dev info from sysfs

---

libckteec/include/pkcs11.h
libckteec/src/serialize_ck.c

The PKCS#11 Specification:
https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/cs01/ pkcs11-spec-v3.1-cs01.pdf
6.1.23 RSA AES KEY WRAP
https://github.com/OP-TEE/optee_os/pull/5647

libckteec: Add RSA AES key wrap serialization
