OP-TEE/optee_client

- Android.mk
Fixes the name of the TEE supplicant binary in Android builds. Indeed,
the current driver expects current->comm to be "tee-supplicant", any
other name results in the process failing to start.
> Android.mk: s/tee_supplicant/tee-supplicant/

- flags.mk
Trying to build optee_client with yocto. Required to
override CC with CC set by yocto environment.
Signed-off-by: Sumit Garg <b49020@freescale.com>
> Make CC configurable via the environment

- Makefile
The previous patch made it possible to override the CC variable.
However, when you don't assign anything at all, there will still be a
value assigned by the implicit variables and hence both libtee.so and
tee-supplicant will be built using the host compiler instead of the
(ARM) cross compiler and as a result of that other builds like xtest etc
will fail. We fix this by adding the argument "--no-builtin-variables"
when calling the individual makefile(s).
Signed-off-by: Joakim Bech <joakim.bech@linaro.org>
> Fixes incorrectly built library and binary

- tee-supplicant/Makefile
- tee-supplicant/src/rpmb.c
- tee-supplicant/src/rpmb.h
- tee-supplicant/src/tee_supplicant.c
This commit adds support for the TEE_RPC_RPMB command, used by OP-TEE
to access the RPMB partition of an eMMC device (/dev/mmcblkXrpmb).
This is independent from the regular filesystem access (TEE_RPC_FS),
so the TEE can use either RPMB or the regular FS (or both) to implement
persistent storage.
RPMB operations are:
- Get device information (partition size, reliable write count)
- Read write counter
- Read and write data
- Program authentication key
The code relies on the ioctl() interface to implement the required
functions. In addition, an emulation layer is provided so that the RPMB
feature may be tested even if an actual eMMC chip is not available, or
if the kernel does not support it. Emulated mode is currently the
default. It can be disabled in the tee-supplicant Makefile …
> Replay Protected Memory Block (RPMB) support

- config.mk
- tee-supplicant/Makefile
- tee-supplicant/src/teec_ta_load.c
- tee-supplicant/tee_supplicant_android.mk
To allow testing of corrupt TA loading on systems where the TA
directory is read-only, try loading TAs first from an alternate
`TEEC_TEST_LOAD_PATH` before the regular path.  This allows the test
to override the TA with one for testing purposes.
Although useful for testing, this should not be enabled for a
production system, since it facilitates replacing a TA with a corrupt
image.
Signed-off-by: David Brown <david.brown@linaro.org>
> Try loading TAs from another writable path

- Makefile
- README.md
Replace 'VERBOSE_BUILD' with 'V' for simplicity and consistency with
other projects.
> Use "make V=1" for verbose build

- libteec/src/tee_client_api.c
- public/tee_client_api.h
Since we have to add support for login method other than TEE_LOGIN_PUBLIC
in the future, remove the limit now.
Signed-off-by: Zeng Tao <prime.zeng@huawei.com>
> Remove the connection_method limit

- tee-supplicant/src/optee_msg_fs.h
- tee-supplicant/src/sql_fs.c
- tee-supplicant/src/tee_supp_fs.c
- tee-supplicant/src/tee_supp_fs.h
- tee-supplicant/src/tee_supplicant.c
- tee-supplicant/src/tee_supplicant.h
As the interface is changed to use proper error codes, the way
parameters are passed is also updated.
> Add new RPC FS functions with useful error codes

- libteec/include/linux/tee.h
- libteec/src/tee_client_api.c
- public/tee_client_api.h
- public/tee_client_api_extensions.h
This is a proposal for implementing the ability for a TA to safely handle memory buffer arguments related to secure buffers. See SWG-186.
This proposal defines a new API in the TEE Client API: `TEEC_RegisterSharedMemoryFileDescriptor()`.
The libteec requests a ioctl to the TEE driver to register the buffer and get a new file descriptor for the TEE shared memory structure. API will simply close this file descriptor to release the shared memory resource.
This PR is related to changes in the TEE linux driver: https://github.com/linaro-swg/linux/pull/26.
> new API to register shared memory from a file descriptor (SWG-186)

- libteec/src/tee_client_api.c
- tee-supplicant/src/tee_supplicant.c
- tee-supplicant/src/teec_ta_load.c
Fixes https://github.com/OP-TEE/optee_os/issues/857 and https://github.com/OP-TEE/optee_os/issues/858
Depends on https://github.com/OP-TEE/optee_os/pull/1227 and https://github.com/OP-TEE/optee_test/pull/150
> Uuid fixes 

- config.mk
- libsqlfs/Makefile
- libsqlite3/Makefile
- libteec/Makefile
- tee-supplicant/Makefile
Tested with:
$ export CFG_WITH_SQLFS=y
$ make
$ make O=build
$ make O=/tmp/build
$ make O=~/build
Suggested-by: Zeng Tao <prime.zeng@hisilicon.com>
> Allow O to be any kind of path (absolute, relative, with ~)

- tee-supplicant/Makefile
sql_fs.c includes an API header (sqlfs.h in libsqlfs) which generates
warnings when built with our default flags. Silence them only for this
particular file, so that we won't miss potential issues in new code.
> tee-supplicant: disable warnings only for sql_fs.c

- tee-supplicant/src/tee_supp_fs.c
The REE handler for open always uses flags O_RDWR at the moment.
This breaks the possibility to use read-only operations on a
read-only mounted filesystem at /data.
Change it to try to open with O_RDWR, if not possible fall back
to O_RDONLY and only fail if that isn't workable either.
If O_RDONLY isn't enough, then the TA should use another means
to get the fs mounted rw for the duration of his write activity.
He will get failures on the write action if not, but that is
fair enough.
Signed-off-by: Andy Green <andy@warmcat.com>
> ree fs rpc: open with best-effort allowing RO data fs

- tee-supplicant/src/tee_supp_fs.c
When source code is built with FORTIFY, it will give an error if you're
doing an open syscall without specifing the mode parameter.
Signed-off-by: Joakim Bech <joakim.bech@linaro.org>
> Use the mode also in open_wrapper

- Android.mk
CFG_TEE_CLIENT_LOG_FILE variable contains the client library log file
path. The correct way to check if the variable is not empty is using
ifneq operator.
Signed-off-by: Ruslan Piasetskyi <ruslan.piasetskyi@gmail.com>
> Android.mk: fix CFG_TEE_CLIENT_LOG_FILE checking

- tee-supplicant/src/rpmb.c
ueventd create block devices under /dev/block/.
Signed-off-by: Zhizhou Zhang <zhizhouzhang@asrmicro.com>
> tee-supplicant: correct block device path for android

- public/tee_client_api.h
ULONG_MAX depends on limits.h.
Fixes: 9faeb1b6b023 ("tee_client_api: Correct max shared memory size define")
> client api: fix ULONG_MAX dependency

- tee-supplicant/src/optee_msg_supplicant.h
- tee-supplicant/src/tee_supplicant.c
Use `OPTEE_MSG_RPC_CMD_xxx` macros from **optee_msg_supplicant.h** rather
than redefining local macros. Add missing macros `OPTEE_MSG_RPC_CMD_SHM_ALLOC/FREE`.
> supplicant: clean duplicated command IDs

- Makefile
- libteec/Makefile
- libteec/include/linux/teec_benchmark.h
- libteec/src/tee_client_api.c
- libteec/src/teec_benchmark.c
- public/tee_bench.h
Related PRs:
Benchmark app:
https://github.com/linaro-swg/optee_benchmark/pull/1
Changes in OP-TEE
https://github.com/linaro-swg/linux/pull/38
https://github.com/OP-TEE/build/pull/124
https://github.com/OP-TEE/optee_os/pull/1365
https://github.com/OP-TEE/optee_client/pull/79
> OP-TEE Benchmark

- tee-supplicant/src/tee_supp_fs.c
Octal numbers are prefered over symbolic values for file access modes.
> Replace file permission symbolic values by octal numbers

- libteec/src/tee_client_api.c
Accroding to TEE Client API Spec section 4.3.8 TEEC_RegisteredMemoryReference,
when handling a TEEC_RegisteredMemoryReference parameter of TEEC_MEMREF_WHOLE
type, the memory region size should read from its parent TEEC_SharedMemory
structure instead of the size described in TEEC_RegisteredMemoryReference
structure.
Signed-off-by: James Kung <kong1191@gmail.com>
> Fix incorrect share memory size

- tee-supplicant/src/tee_supplicant.c
I know that optee_os' strategy is to first pass all-zeroed parameters so that it gets back the size to allocate.
But let's say that for some reason the allocation is invalid, that it to say it was successful, but not good enough for TA copying. That can happen for instance if the allocated size is too small, or if the allocation was not done by the supplicant itself (this is what I did, I wrongfully tried to do it by calling `tee_shm_alloc` from kernel space and pass that as buffer).
In that case, during the second call, `try_load_secure_module` will return `TA_BINARY_FOUND`, letting the caller believe that the copy worked as expected.
I don't know if this is the right fix, and it probably has consequences on the linux driver and/or on optee_os, but this is a start!
> tee-supplicant: Report OK only for actual loading

- Android.mk
- libteec/Makefile
- libteec/include/teec_benchmark.h
- libteec/src/tee_client_api.c
- libteec/src/teec_benchmark.c
Some cleanup which should also fix a build error on Android:
external/optee_client/libteec/src/tee_client_api.c:556: error: undefined reference to 'bm_timestamp'
external/optee_client/libteec/src/tee_client_api.c:592: error: undefined reference to 'bm_timestamp'
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)
- Move include/linux/teec_benchmark.h up one level, because this file
is not related to the Linux TEE driver
- Make bm_timestamp() a no-op static inline if CFG_TEE_BENCHMARK != y
- Remove conditional compilation in teec_benchmark.c, instead, add the
file to the build only when CFG_TEE_BENCHMARK = y
- Declare benchmark_check_mode() static in teec_benchmark.c, since it
is not used anywhere else
Signed-off-by: Jerome Forissier …
> libteec: benchmark cleanup

- libteec/src/teec_benchmark.c
Fix unsupported exclusive issue , which occurs when using gcc builtin
atomic
__sync_fetch_and_add();, which is unfolded into LDXR/STLXR pair
(aarch64).
Currently, __sync_fetch_and_add() is used in bm_timestamp() for updating
head/tail
of timestamp per-cpu ringbuffers.
```
Fixes: https://github.com/OP-TEE/optee_client/issues/99
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>
```
> rpi3: fix unsupported exclusive access issue

- public/tee_client_api.h
- public/tee_client_api_extensions.h
- public/teec_trace.h
The tee client api has got no restriction for cplusplus program,
simplely add extern "c" in this patch to support this feature.
Signed-off-by: Zeng Tao <prime.zeng@hisilicon.com>
> tee_client_api: support calling libteec from cplusplus

- libteec/include/linux/tee.h
- libteec/src/tee_client_api.c
- public/tee_client_api.h
- tee-supplicant/src/tee_supplicant.c
This patch is the userspace part of dynamic shared memory in OP-TEE (refer to https://github.com/OP-TEE/optee_os/pull/1232). This patch is authred by @jenswi-linaro, I just tidied it a bit and rebased on current master.
This patch utilizes new ioctl that allows client application to share any buffer with OP-TEE.
> tee_client_api: register user memory

- tee-supplicant/src/tee_supp_fs.c
CFG_RPMB_FS=y and RPMB_EMU=0(use EMMC RPMB device). Power down when
writing file without the O_SYNC flag, dirf.db was cached by kernel,
some very old (more than two generations) version was in the file
system. If dirf.db and dirfile.db.hash (residing in RPMB) differ by
two versions, it will cause TEE_ERROR_SECURITY, and the file data
will lost.
Add O_SYNC flag in open file to fix this issue.
(fixed by Jens Wiklander)
Signed-off-by: Jianhui Li <airbak.li@hisilicon.com>
Tested-by: Jianhui Li <airbak.li@hisilicon.com> (Hisilicon)
> tee-supplicant: REE fs open file with O_SYNC flag

- tee-supplicant/src/tee_socket.c
Fixes gcc warning:
src/tee_socket.c: In function 'poll_with_timeout.constprop':
src/tee_socket.c:361:28: error: 'until.tv_nsec' may be used uninitialized in this function [-Werror=maybe-uninitialized]
diff.tv_nsec = a->tv_nsec - b->tv_nsec;
~~~~~~~~~~~^~~~~~~~~~~~
src/tee_socket.c:382:18: note: 'until.tv_nsec' was declared here
struct timespec until;
^~~~~
src/tee_socket.c:360:26: error: 'until.tv_sec' may be used uninitialized in this function [-Werror=maybe-uninitialized]
diff.tv_sec = a->tv_sec - b->tv_sec;
~~~~~~~~~~^~~~~~~~~~~
src/tee_socket.c:382:18: note: 'until.tv_sec' was declared here
struct timespec until;
^~~~~
cc1: all warnings being treated as errors
> tee-supplicant: fix gcc warning

- tee-supplicant/src/tee_socket.c
Fixes compilation warnings on Android:
optee_client/tee-supplicant/src/tee_socket.c:551:12: error: comparison of integers of different signs: 'socklen_t' (aka 'int') and 'unsigned int' [-Werror,-Wsign-compare]
if (slen < sizeof(*sain))
~~~~ ^ ~~~~~~~~~~~~~
optee_client/tee-supplicant/src/tee_socket.c:561:12: error: comparison of integers of different signs: 'socklen_t' (aka 'int') and 'unsigned int' [-Werror,-Wsign-compare]
if (slen < sizeof(*sain6))
~~~~ ^ ~~~~~~~~~~~~~~
optee_client/tee-supplicant/src/tee_socket.c:577:12: error: comparison of integers of different signs: 'socklen_t' (aka 'int') and 'unsigned int' [-Werror,-Wsign-compare]
if (slen < sizeof(*sain))
~~~~ ^ ~~~~~~~~~~~~~
optee_client/tee-supplicant/src/tee_socket.c:587:12: error: comparison of integers of different signs: …
> tee-supplicant: cast sizeof(x) to socklen_t

- public/CMakeLists.txt
Seems to get the jobs done:
```bash
$ cmake -DCMAKE_INSTALL_PREFIX=/tmp/client ..
...
$ make install
....                 
-- Installing: /tmp/client/include/tee_bench.h                                 
-- Installing: /tmp/client/include/tee_client_api.h                            
-- Installing: /tmp/client/include/tee_client_api_extensions.h                 
-- Installing: /tmp/client/include/teec_trace.h     
```
> Do not export CMakeLists.txt when running install

- Makefile
- config.mk
to workaorund export restriction when building for android platform
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
> Makefile and config.mk: remove export in config.mk

- tee-supplicant/CMakeLists.txt
Enables RPMB emulation by default also when compiling with cmake.
> tee-supplicant: cmake: enable RPMB emulation by default

- tee-supplicant/src/gprof.c
Avoids a compile error with using GCC 8.x with CFG_TA_GPROF_SUPPORT=y:
src/gprof.c: In function ‘gprof_process’:
src/gprof.c:97:35: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 4 [-Werror=format-truncation=]
snprintf(vers, sizeof(vers), ".%d", id - 1);
^~
src/gprof.c:97:33: note: directive argument in the range [1, 2147483646]
snprintf(vers, sizeof(vers), ".%d", id - 1);
^~~~~
src/gprof.c:97:4: note: ‘snprintf’ output between 3 and 12 bytes into a destination of size 5
snprintf(vers, sizeof(vers), ".%d", id - 1);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
> tee_supplicant: gprof: fix compile error

- libteec/Makefile
The Makefile currently generates a libteec.so file that has the SONAME "libteec.so.1.0". By contrast, the CMake script generates libteec.so with the SONAME "libteec.so.1". An application that has been linked against the Makefile version of libteec.so expects the file libteec.so.1.0 to be present in the runtime environment. However, no such file is generated by the CMake script which means the application cannot be executed in an environment for which libteec was built with CMake.
The proposed change modifies the Makefile so that it generates libteec.so and the corresponding symlinks in exactly the same way as the CMake script. That is, both the Makefile and the CMake script generate a library with the SONAME "libteec.so.1" as well as the symlinks libteec.so and libteec.so.1.
An …
> libteec: Makefile: Generate .so files the same way as CMake

- Makefile
Change GNU makefile to default install **tee-supplicant** in target directory **/bin** instead of **/sbin**.
This change aligns the GNU makefile install sequence with the CMake install sequence.
> tee-supplicant: fix install path in GNU makefile

- libteec/CMakeLists.txt
- tee-supplicant/CMakeLists.txt
CMake variables BUILD_STATIC_LIBS and BUILD_SHARED_LIBS
set constraints on libraries and executable linkage.
With this change OP-TEE client CMake script builds and installs the
embedded files with the expected linkage configuration.
Reported-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
> cmake: support BUILD_STATIC_LIBS/BUILD_SHARED_LIBS

- libteec/src/tee_client_api.c
external/optee_client/libteec/src/tee_client_api.c:488:11: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
uint8_t data[sizeof(struct tee_ioctl_open_session_arg) + p_sz];
^
external/optee_client/libteec/src/tee_client_api.c:566:11: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
uint8_t data[sizeof(struct tee_ioctl_invoke_arg) + p_sz];
^
Fixes: 9dbc61b3 ("libteec: fix build warnings")
Fixes: https://github.com/OP-TEE/optee_client/issues/152
> libteec: fix clang build errors

- libteec/src/tee_client_api.c
- tee-supplicant/src/rpmb.c
- tee-supplicant/src/tee_supplicant.c
Prefer using = { } rather than explicit memset() for default
initialization of structure local variables. The rational is that
memset() are implemented below variable definition block whereas
such default initialization is more explicit if done exactly where
the variable is define, non structured/enumerated type local variables.
When not possible, use = { 0 } or memset().
> Initialize structured local variable where defined

- tee-supplicant/src/rpmb.c
Prior to this patch was ioctl_emu_read_ctr() calculating a MAC over
among other things the uninitialized "op_result". "op_result" often
happens to be 0 which is the same as RPMB_RESULT_OK which is returned by
compute_hmac() on success. However, this field is not initialized before
calculating the MAC so it could very well differ resulting in an invalid
MAC. This patch fixes this by initializing "op_result" to RPMB_RESULT_OK
before calculating the MAC.
> tee-supplicant: ioctl_emu_read_ctr(): MAC correct data

- Android.mk
- config.mk
- tee-supplicant/CMakeLists.txt
- tee-supplicant/src/tee_supp_fs.c
CFG_TEE_DATA_PATH confuses users because it's only used as a prefix for
CFG_TEE_LOGS_PATH and not the actual root path for the TEE data dir as
described. The actual root path is $(TEE_FS_PARENT_PATH)/tee as can be
seen under tee_supp_fs_init() in tee-supplicant/src/tee_supp_fs.c, so
just get rid of CFG_TEE_DATA_PATH.
Next, we move "/tee" from tee_supp_fs_init() to CFG_TEE_FS_PARENT_PATH,
because otherwise, we have the beginning part of the path in a makefile
(config.mk) and the ending in code (tee_supp_fs_init()), which seems
messy to manage and error prone. E.g. CFG_TEE_LOGS_PATH (or any of its
subsequently derived configs) depends on the actual full path of the TEE
fs, so we can just set
CFG_TEE_LOGS_PATH ?= $(CFG_TEE_FS_PARENT_PATH)/logs
rather than
CFG_TEE_LOGS_PATH ?= …
> simplify use of TEE fs related configs

- Makefile
- tee-supplicant/CMakeLists.txt
- tee-supplicant/Makefile
- tee-supplicant/src/optee_msg_supplicant.h
- tee-supplicant/src/prof.c
- tee-supplicant/src/prof.h
- tee-supplicant/src/tee_supplicant.c
- tee-supplicant/tee_supplicant_android.mk
Make gprof dump framework common to utilize for ftrace buffer dump
support.
This is inline to optee_os support for ftrace feature for user TAs, PR: https://github.com/OP-TEE/optee_os/pull/2912.
Looking forward to your comments.
Regards,
Sumit
> [RFC] tee-supplicant: Add ftrace buffer dump support

- config.mk
- libteec/CMakeLists.txt
CFG_TEE_CLIENT_LOG_FILE was originally /data/teec.log. Commit 9a63135b
("Android.mk & config.mk: move teec.log/teesupp.log under /data/tee")
introduced CFG_TEE_LOGS_PATH which placed teec.log under
/data/tee/logs/, but in nowhere (here or build.git) do we create the
'logs' dir, so fopen /data/tee/logs/teec.log fails and teec.log is
never created. To make things simple, remove CFG_TEE_LOGS_PATH and
just place teec.log under /data/tee.
> config.mk: get rid of CFG_TEE_LOGS_PATH

- .travis.yml
Travis CI have switched their default distribution from Ubuntu 14.04.5
to 16.04.6. Now we have the following build error:
CC      src/tee_client_api.c
In file included from /usr/include/errno.h:28:0,
from src/tee_client_api.c:28:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
The missing file is in the libc6-dev-armhf-cross package.
> Travis: install package libc6-dev-armhf-cross

- Makefile
- config.mk
- tee-supplicant/CMakeLists.txt
By default enables ftrace and gprof dumping. Not used unless secure
world decides to dump something.
> [RFC] tee-supplicant: default enable ftrace a gprof

- config.mk
- tee-supplicant/CMakeLists.txt
- tee-supplicant/Makefile
- tee-supplicant/src/prof.h
- tee-supplicant/tee_supplicant_android.mk
Rename ftrace config macro from CFG_TA_FTRACE_SUPPORT to
CFG_FTRACE_SUPPORT as now with syscall function graph feature,
scope of ftrace has been enlarged to profile OP-TEE core as well.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
> tee-supplicant: Rename ftrace config macro

- tee-supplicant/src/prof.c
Function prof_process() creates a file in /tmp which is named after
the UUID passed to the function. The format of the UUID is not the
usual one; a dash is missing. Add it.
> ftrace, gprof: fix format of UUID string in file name

- libckteec/src/ck_helpers.c
- libckteec/src/ck_helpers.h
- libckteec/src/pkcs11_api.c
For sanity of the library and service implementation, assert the
CKR_* return value before returning to caller from CK API functions.
This change asserts return values for C_Initialize() and C_Finalize().
> libckteec: assert api init/release functions return value compliance

- libckteec/src/invoke_ta.c
- libckteec/src/invoke_ta.h
Add new API function ckteec_register_shm() to register in OP-TEE OS
a piece of Linux userland memory which a PKCS11 TA service will access
to, as an input data or output data buffer in a cryptography ciphering
sequence.
> libckteec: invocation api function to register shared memory

- Makefile
libckteec depends on libteec, therefore the build-libckteec target
needs to have build-libteec as a prerequisite.
Fixes the following build error:
$ make -j`nproc`
[...]
<...>/bin/ld: cannot find -lteec
collect2: error: ld returned 1 exit status
Makefile:47: recipe for target '<...>/out/libckteec/libckteec.so.0.1.0' failed
make[2]: *** [<...>/out/libckteec/libckteec.so.0.1.0] Error 1
> libckteec: Makefile: add missing dependency

- libckteec/src/invoke_ta.c
Use PRIu32 specifiers in debug trace instead of casting the
traced values.
> libckteec: use PRIu32 instead of casts

- .travis.yml
As per the Travis docs at
https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth to
avoid performing git clones with limited depth, the depth should be set
to "false", not to a large magic number.
Signed-off-by: David Brown <david.brown@linaro.org>
> ci: travis: Use proper construct for full clone

- libckteec/src/invoke_ta.c
- libckteec/src/invoke_ta.h
When invoking PKCS11 TA invocation parameters #2 and #3 can refer to output data buffer. This change adds means for caller to get the effective output data length.
An second commit defines helper function  `ckteec_invoke_*()` for invoking PKCS11 TA with reduced arguments.
> libckteec: correct ckteec_invoke_ta() prototype to handle output data size

- libckteec/CMakeLists.txt
- libckteec/Makefile
- libckteec/include/pkcs11_ta.h
- libckteec/src/ck_helpers.h
- libckteec/src/local_utils.h
- libckteec/src/pkcs11_api.c
- libckteec/src/pkcs11_token.c
- libckteec/src/pkcs11_token.h
Implement PKCS#11 API functions `C_GetInfo()`, `C_GetSlotList()` and `C_GetSlotInfo()`.
Related to P-R https://github.com/OP-TEE/optee_os/pull/3644.
> libckteec: pkcs11 slot info

- libckteec/src/pkcs11_api.c
- libckteec/src/pkcs11_token.c
- libckteec/src/pkcs11_token.h
Implement C_GetTokenInfo() API function to retrieve information about
a token implemented by the PKCS11 TA.
Helper function ta2ck_token_info() converts token information data from
TA API into compliant Cryptoki API.
Depends on https://github.com/OP-TEE/optee_os/pull/3656.
> libckteec: implement C_GetTokenInfo()

- libteec/include/linux/tee.h
- libteec/src/tee_client_api.c
- public/tee_client_api.h
Refering to GPTS test suite v2.0.0.1-2016-11-09 id de-14-33
Refer to the TEEC_RegisterSharedMemory function for error conditions
which can be triggered during temporary registration of a memory region.
The CA needs to be able to send a null pointer to the TA. Previously
this was done by allocating a block of shared memory but setting the
size to 0.  This did not allow sending a non-NULL pointer with size 0,
this failing GPTS tests.
This change flags a NULL pointer with an invalid shared memory id rather
than size 0.
Signed-off-by: Michael Whitfield <michael.whitfield@nxp.com>
Signed-off-by: Cedric Neveux <cedric.neveux@nxp.com>
> Flag NULL pointer using invalid shm id

- tee-supplicant/src/tee_supplicant.c
If request->send.num_params is assigned a large value, there could be
an overflow when computing data.buf_len. Cast to __u64 to avoid a
32-bit computation.
> tee-supplicant: cast to __u64 to avoid potential overflow

- libckteec/Makefile
- libteec/Makefile
At least Yocto and ptxdist provide the option to invoke the linker with
-Wl,--as-needed, which will only mark the libraries as needed if they
are used by the binary or library. However this assumes that the object
files are passed before the shared libraries, move the LFLAGS for
libctkteec and libteec to the end of linker invocation to support this.
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>
> libckteec/libteec: move LFLAGS to end of call

- libteec/src/tee_client_api.c
Change teec_pre_process_partial() to reject out of bound memref
invocation parameters before TEE is invoked.
This change is needed in case dynamic SHM is disabled in which case
memory reference used as TEE invocation parameters may have been
allocated using a wider buffer than the one provided by client. In
such case, TEE may not able to detect out of bound references
since original client buffer very location (start and size) do not
reach the TEE.
Reported-by: Sumit Garg <sumit.garg@linaro.org>
Suggested-by: Jens Wiklander <jens.wiklander@linaro.org>
> libteec: report out of bound memory references from client library

- libteec/src/tee_client_api.c
Fix libteec to return TEEC_ERROR_BAD_PARAMETERS when client registers
a shared memory reference for a NULL buffer as per GPD specification
v1.0 that states "The buffer field MUST point to the memory region to
be shared, and MUST not be NULL.
Prior this change TEEC_RegisterSharedMemory() called with a NULL buffer
reference returned TEEC_ERROR_OUT_OF_MEMORY when dynamic shared memory
is enabled and successfully registered a memory reference when dynamic
shared memory is disabled. With this change the API function returns
TEEC_ERROR_BAD_PARAMETERS.
> libteec: registration shared memory for a null buffer is invalid

- README.md
This fixes a broken link.
Signed-off-by: Joakim Bech <joakim.bech@linaro.org>
> readme: update the link to optee_client documentation

- libteec/include/linux/tee.h
- libteec/src/tee_client_api.c
- tee-supplicant/src/prof.c
- tee-supplicant/src/tee_socket.c
- tee-supplicant/src/tee_supp_fs.c
- tee-supplicant/src/tee_supplicant.c
- tee-supplicant/src/tee_supplicant.h
It seems that tee.h never was synced with the kernel after the patches finally landed upstream.
The union in struct tee_ioctl_param is now removed. Some parts of the code seems to become a bit harder to read. I'm not sure what's the best way of addressing that. Any idea?
> Sync tee.h with Linux kernel v5.6

- config.mk
ARM_TOOLCHAIN_DIR and ARM_GCC_PREFIX aren't used for a long time and only mentioned in config.mk now.
This could be confusing, thus it's better to remove them.
> Remove obsolete toolchain variables reference in config.mk

- flags.mk
Some build systems set CFLAGS in environment before the build, but they
got overridden by CFLAGS immediate assignment operator.
Replace immediate assignment with append directive, so the former
definition of CFLAGS gets properly expanded.
Signed-off-by: Andrey Zhizhikin <andrey.z@gmail.com>
> flags: do not override CFLAGS from host

- libckteec/CMakeLists.txt
- libckteec/Makefile
The libckteec CMakeList.txt and Makefile both have the SONAME wrong.
With the current version (0.1.0), SONAME should be libckteec.so.0, but:
- CMakeList.txt sets it to libckteec.so.ckteec
- Makefile sets it to libckteec.so.0.1.0
This commit fixes both build environments.
Reported-by: Guillaume Gardet <guillaume.gardet@opensuse.org>
> libckteec: fix SONAME to be libckteec.so.<MAJOR_VERSION>

- libckteec/CMakeLists.txt
Remove SHARED from add_library call to avoid the following build failure
when the toolchain does not support shared library:
```
[ 78%] Linking C shared library libckteec.so
/home/buildroot/autobuild/instance-3/output-1/host/lib/gcc/microblazeel-buildroot-linux-uclibc/9.3.0/../../../../microblazeel-buildroot-linux-uclibc/bin/ld: FDE encoding in /home/buildroot/autobuild/instance-3/output-1/host/microblazeel-buildroot-linux-uclibc/sysroot/usr/lib/libc.a(close.os)(.eh_frame) prevents .eh_frame_hdr table being created
/home/buildroot/autobuild/instance-3/output-1/host/lib/gcc/microblazeel-buildroot-linux-uclibc/9.3.0/../../../../microblazeel-buildroot-linux-uclibc/bin/ld: FDE encoding in /home/buildroot/autobuild/instance-3/output-1/host/microblazeel-buildroot-linux-uclibc/sysroot/usr/lib/lib …
```
> libckteec/CMakeLists.txt: fix static build

- libteec/src/tee_client_api.c
- public/tee_client_api.h
Adds a fallback option to TEEC_RegisterSharedMemory() where
TEE_IOC_SHM_REGISTER fails, likely due to the caller supplying read-only
memory. Instead of failing and burden the caller to handle this,
implement it here instead. If TEE_IOC_SHM_REGISTER fails, malloc() a
buffer and register that as a shadow buffer instead.
> libteec: fix TEEC_RegisterSharedMemory() with a fallback option

- libteec/src/tee_client_api.c
If TEE or TEE driver doesn't support the capability "TEE_GEN_CAP_MEMREF_NULL",
"memref_null" is not set in the TEEC_Context. In such cases, while
handling parameters of type TEEC_TempMemoryReference, a call to
TEEC_RegisterSharedMemory() will return an error for NULL pointers.
Using NULL pointer is a valid use case and should not result in errors.
Use TEEC_AllocateSharedMemory() to avoid errors in such cases.
Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>
> libteec: Handle NULL pointer when using TEEC_TempMemoryReference

- tee-supplicant/Makefile
At the moment the RPMB_EMU variable in the Makefile uses a simple
assignment and unconditionally sets the variable.
Move it to a conditional assignment and allow people to override it
from the command line with:
CROSS_COMPILE=aarch64-linux-gnu- RPMB_EMU=0 make
Signed-off-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
> tee-supplicant: make RPMB_EMU a conditional assignment

- .travis.yml
Change the checkpatch URL from linux master to linux-next to
fix the following error and hopefully be more convenient in the
future:
Global symbol "$gitroot" requires explicit package name [...]
This patch is similar to the one recently merged in optee_os [1].
Link: [1] https://github.com/OP-TEE/optee_os/commit/5d50cc958c9d
> ci: travis: download checkpatch.pl from linux-next

- libteec/src/tee_client_api.c
teec_pre_process_operation()  returns an error code of teec_pre_process_tmpref() directly when it failed (such as allocate a very large size of SHM). In this situation, the shm->id are still zero. It result in wrong error handling. When TEEC_ReleaseSharedMemory() is called in function teec_free_temp_refs(), it may 
close a wrong fd 0 since the shm->id is not -1 (the initial value is zero).
> libteec: Fix the initial value of shm->id in teec_pre_process_operation()

- libckteec/src/pkcs11_processing.c
- libckteec/src/serialize_ck.c
- libckteec/src/serializer.c
Replace { } initializer by { 0 } to fix the following build failure with gcc 4.8:
```
libckteec/src/pkcs11_processing.c: In function 'ck_create_object':
libckteec/src/pkcs11_processing.c:22:9: error: missing initializer for field 'buffer' of 'struct serializer' [-Werror=missing-field-initializers]
struct serializer obj = { };
^
```
Fixes: http://autobuild.buildroot.org/results/a3d663adb943aee814180f01d6e153b3309be962
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
> libckteec: replace { } initializer by { 0 }

- libckteec/src/pkcs11_processing.c
If a valid input buffer with size 0 is passed in an update
operation like C_SignUpdate()/C_VerifyUpdate()/C_EncryptUpdate()/
C_DecryptUpdate(), current implementation return error
CKR_BAD_ARGUMENTS. This is actually not an error scenario.
Ideally, we should not perform any cryptographic operation
and return CKR_OK if other parameters are valid. Hence register
a shared memory buffer in such scenarios also and pass it to the TA.
Suggested-by: Etienne Carriere <etienne.carriere@linaro.org>
Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>
> libckteec: Allow 0 length input buffer  for update operations.

- libckteec/include/pkcs11_ta.h
- libckteec/src/invoke_ta.c
- libckteec/src/pkcs11_token.c
Please see https://github.com/OP-TEE/optee_os/pull/4222 for testing and usage instructions.
Implements:
https://github.com/OP-TEE/optee_os/issues/3946
> pkcs11: Add TEE Identity based authentication support

- libckteec/src/serialize_ck.c
It is fine for callee to allocate more memory than what is
needed for any attribute. Earlier for attributes of type
ulong, a strict check was there which returned error
if callee passed buffer greater than the required size.
Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>
> libckteec: serialize: fix check for ULONG type entries

- .gitignore
- Makefile
- config.mk
- public/tee_plugin_method.h
- tee-supplicant/CMakeLists.txt
- tee-supplicant/Makefile
- tee-supplicant/src/optee_msg_supplicant.h
- tee-supplicant/src/plugin.c
- tee-supplicant/src/plugin.h
- tee-supplicant/src/tee_supplicant.c
This framework makes the supplicant a bit more flexible
in terms of providing services. Any external TEE services
can be designed as a tee-supplicant plugin.
It makes it easy to:
- add new features in the supplicant that aren't needed in upstream,
e.g. Rich OS specific services;
- sync upstream version with own fork;
To create a plugin developers should implement the
'struct plugin_method' and a bind function.
See public/tee_plugin_method.h file.
As an example this patch implements a 'syslog' plugin
and its Makefile. The plugin helps to log any
information from TEE to system journal.
The plugin framework is based on new RPC call - 'OPTEE_MSG_RPC_CMD_PLUGIN'.
This RPC is an unified interface between TEE and any plugins.
Every plugin has own name based on UUID. TEE has access to
plugins …
> tee-supplicant: add a framework for loadable plugins

- libckteec/src/invoke_ta.c
Fixes the following build error by including `sys/types.h` to ensure `gid_t` is defined:
```text
[ 65%] Building C object libckteec/CMakeFiles/ckteec.dir/src/invoke_ta.c.o
src/invoke_ta.c: In function ‘ckteec_invoke_init’:
src/invoke_ta.c:245:2: error: unknown type name ‘gid_t’; did you mean ‘pid_t’?
245 |  gid_t login_gid = 0;
|  ^~~~~
|  pid_t
src/invoke_ta.c:267:38: error: ‘gid_t’ undeclared (first use in this function); did you mean ‘pid_t’?
267 |    if (errno == ERANGE || tmpconv > (gid_t)-1 ||
|                                      ^~~~~
|                                      pid_t
src/invoke_ta.c:267:38: note: each undeclared identifier is reported only once for each function it appears in
src/invoke_ta.c:274:23: error: expected ‘;’ before ‘tmpconv’
274 |    login_gid = …
```
> libckteec: add missing include for gid_t

- tee-supplicant/src/tee_supplicant.c
Prior to this change tee-supplicant, when called with -d,
first opened /dev/teeprivX, and called daemon(3) later.
This implied that a file descriptor associated with the
supplicant device transferred from one process to another.
This may conflict with security policies related to tee device
file descriptors. Since TEE client ID is tied to a process,
transferring such a sensitive thing as a tee device handle
between processes might be discouraged.
Reorder the two: first daemonize, and open the tee device later.
---
An example of how such a security policy could be implemented can be seen at https://github.com/parport0/linux/tree/tee-fd.
> tee-supplicant: daemonize before opening a supplicant device

- libckteec/include/pkcs11_ta.h
- libckteec/src/pkcs11_api.c
- libckteec/src/pkcs11_processing.c
- libckteec/src/pkcs11_processing.h
- libckteec/src/serialize_ck.c
Implements support for digest operations as specified in:
PKCS #11 Cryptographic Token Interface Base Specification Version 2.40
Plus Errata 01
5.10 Message digesting functions
> libckteec: Add support for digest operations

- libckteec/src/invoke_ta.c
libckteec: add missing unistd.h for group ID type
Include missing unistd.h to support type gid_t. This change fixes [1].
Link: [1] http://autobuild.buildroot.net/results/34b9946e6d59112a7eead304933534ad4739a84c/build-end.log
> libckteec: add missing unistd.h for group ID type

- libckteec/src/serialize_ck.c
An attribute template (type, pValue, ulValueLen) provided with
C_GetAttributeValue() may have pValue field as NULL pointer with
a zero/non-zero ulValueLen field. In these cases TEE should modify
the ulValueLen to hold the exact length of the specified attribute
for the object.
In the current code, for non-zero ulValueLen with pValue as NULL
pointer, an attempt was being made to read the ulValueLen length
data from NULL pointer resulting in segmentation fault. To fix this,
in such scenarios, pass ulValueLen as 0 to TEE.
Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>
> libckteec: serialize: Fix crash with NULL pValue in attribute

- tee-supplicant/src/rpmb.c
On some eMMC devices, the mix of RPMB and normal MMC commands can result
in GENERAL FAILURE, which then forces OP-TEE to mark the RPMB device
as dead (part of the rollback vulnerability fix).
In order to work around this problem, the linux kernel also supports
sending all the required MMC_IOC commands in one single multiple ioctl
command request, which forces the RPMB commands to be serialized,
avoiding the issue.
As MMC_IOC_MULTI_CMD is available since linux 4.3, we should be safe to
use it by default on read / write block operations.
For reference, this issue is also nicely described at the
https://www.mail-archive.com/linux-mmc@vger.kernel.org/msg17589.html.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> tee-supplicant: rpmb: switch to MMC_IOC_MULTI_CMD

- libteec/src/tee_client_api.c
- tee-supplicant/src/tee_supplicant.c
Allocate page aligned shared memory buffer guarantee that each shared
memory buffer doesn't accidentally share a page of memory or they may
become aliased when mapped in secure world. This is normally not a big
problem but may make it a bit harder to track down buffer overruns in
shared memory buffers.
In a post Arm v8.4 architecture with FF-A [1] there's trouble since it's
not permitted to share the same physical page twice.
[1] https://developer.arm.com/documentation/den0077/latest
Needed by https://github.com/OP-TEE/optee_os/pull/4509
> Allocate page aligned shared memory buffers

- libckteec/src/invoke_ta.c
Return CKR_CANT_LOCK if mutex fails at lib initialization. This
conforms with the PKCS#11 specification v2.40-errata01. Preserve
the exit cases on mutex issues when unlocking and in C_Finalize().
> libckteec: return CKR_CANT_LOCK if mutex fails at lib initialization

- libckteec/include/pkcs11_ta.h
- libckteec/src/pkcs11_api.c
- libckteec/src/pkcs11_processing.c
- libckteec/src/pkcs11_processing.h
- libckteec/src/serialize_ck.c
Add support for elliptic curve key pair generation, signing and verification operations.
Goes with:
- https://github.com/OP-TEE/optee_os/pull/4453
- https://github.com/OP-TEE/optee_test/pull/503
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
> libckteec: Add elliptic curve support

- tee-supplicant/src/plugin.c
The readdir(3) man page mentions:
```
Currently, only some filesystems (among them: Btrfs, ext2, ext3, and
ext4) have full support for returning the file type in d_type. All
applications must properly handle a return of DT_UNKNOWN.
```
Which is exactly the case on my nitrogen6x test system based on YOCTO
gatesgarth even using ext4:
```
getdents64(4</usr/lib/tee-supplicant/plugins>,
[{d_ino=3269, d_off=375390918, d_reclen=64, d_type=DT_UNKNOWN,
d_name="f07bfc66-958c-4a15-99c0-260e4e7375dd.plugin"}, …], 32768) = 112
```
Even the regular test plugin for the tee-supplicant is identified as
DT_UNKNOWN, preventing the supplicant from loading the plugin.
Instead concatenate both the path and the filename and call stat(2) to
check if the resulting complete path is a regular file.
Signed-off-by: …
> tee-supplicant: plugin: remove regular file type check

- Makefile
optee_client_config.mk should be installed to a more traditional and
common folder such as INCLUDEDIR instead of being installed directly to
DESTDIR (which can end up as / depending on the packaging system used).
This was noticed when packaging optee-client for OE, as DESTDIR gets set
to the deploy folder, which is later used as root for packaging
optee-client.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> Makefile: install optee_client_config.mk at INCLUDEDIR

- tee-supplicant/src/tee_supplicant.c
The shared memory size got from tee_shm object already strips offset
from total buffer size.
The offset substraction breaks memref parameters through RPC when
applying offset to them.
Signed-off-by: Timothée Cercueil <timothee.cercueil@st.com>
> tee_supplicant.c: Fix shared memory size retrieval from OPTEE

- libckteec/src/pkcs11_processing.c
As specified in:
PKCS #11 Cryptographic Token Interface Base Specification
Version 2.40 Plus Errata 01
5.2 Conventions for functions returning output in a variable-length buffer
When querying size of returned variable-length buffer actual value of
*pulBufLen for input can be anything as long as pBuf is NULL and pulBufLen
is not NULL.
Related PRs:
- https://github.com/OP-TEE/optee_test/pull/524
> libckteec: Fix signature size query for C_Sign/C_SignFinal

- libckteec/src/pkcs11_processing.c
As specified in:
PKCS #11 Cryptographic Token Interface Base Specification
Version 2.40 Plus Errata 01
5.2 Conventions for functions returning output in a variable-length buffer
When querying size of returned variable-length buffer actual value of
*pulBufLen for input can be anything as long as pBuf is NULL and pulBufLen
is not NULL.
Fixes problem found during reviewing PR:
https://github.com/OP-TEE/optee_os/pull/4469
> libckteec: Fix wrapped key output buffer size query for C_WrapKey

- libckteec/src/pkcs11_processing.c
As specified in:
PKCS #11 Cryptographic Token Interface Base Specification
Version 2.40 Plus Errata 01
5.2 Conventions for functions returning output in a variable-length buffer
When querying size of returned variable-length buffer actual value of
*pulBufLen for input can be anything as long as pBuf is NULL and pulBufLen
is not NULL.
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
Related PR:
- https://github.com/OP-TEE/optee_test/pull/529
> libckteec: Fix output buffer size query for C_Encrypt*/C_Decrypt*

- libckteec/src/pkcs11_token.c
Some libraries registers notify callbacks to Cryptoki just to be on safe side
without having intention of aborting the operation.
Possibly uses for notify callback are defined in:
PKCS #11 Cryptographic Token Interface Base Specification
Version 2.40 Plus Errata 01
5.16 Callback functions
"A typical use of a surrender callback might be to give an application user
feedback during a lengthy key pair generation operation.  Each time the
application receives a callback, it could display an additional “.” to the user."
OP-TEE do not currently have this kind of mechanism to abort key generation
thus no need for such callback.
If callee has registered for such callback and is prepared to display progress
indication or abort the progress it will just never happen. User application
receives …
> libckteec: In C_OpenSession() allow notify callback to be specified

- libteec/src/tee_client_api.c
Signed-off-by: Sadiq Hussain <sadiq.muchumarri@intel.com>
> libteec: Convert ioctl errno to an appropriate TEEC error

- libckteec/src/serialize_ck.c
Add support for *_GENERAL MD5 and SHA based HMAC mechanisms.
> libckteec: Add support for more HMAC mechanisms

- libckteec/include/pkcs11.h
- libckteec/include/pkcs11_ta.h
Synchronize pkcs11 TA interface for certificate support.
Add necessary `pkcs11.h` definitions so that `xtest` can be compiled for pkcs11 certificate tests.
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
Related PRs:
- https://github.com/OP-TEE/optee_os/pull/4797
- https://github.com/OP-TEE/optee_test/pull/542
> libckteec: Add certificate object support

- libckteec/src/serialize_ck.c
Add support for CKM_AES_CMAC* mechanisms.
> libckteec: Add support for CKM_AES_CMAC_GENERAL

- libckteec/src/serialize_ck.c
CK_ULONG conversion was forgotten on first batch so this adds them.
Also fixes error value returned when provided CK_ULONG value is too small.
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
Related PRs:
- https://github.com/OP-TEE/optee_os/pull/4797
- https://github.com/OP-TEE/optee_test/pull/542
> libckteec: Fix X.509 certificate attribute handlings

- tee-supplicant/src/tee_socket.c
Adds special treatment if recvmsg() returns error with EINTR, in that
case the was the syscall interrupted by delivery of a signal and we
should just try again with the same arguments.
> tee-supplicant: recv_with_out_flags(): check EINTR

- libteec/src/tee_client_api.c
Without dynamic shared memory enabled (CFG_CORE_DYN_SHM=n) temporary
memrefs uses a shadow buffer to transport data to and from the kernel.
Prior to this patch in case the out length of such a buffer is larger
than the initial size then no copy out is performed even though some
relevant data may be available. Fix this by copying out as much data as
the shadow buffer can hold.
Fixes: https://github.com/OP-TEE/optee_os/issues/5101
> libteec: copy out partial shadow buffer

- libckteec/include/pkcs11.h
- libckteec/src/serialize_ck.c
This commit integrates previous work done by Etienne Carriere and Vesa
Jääskeläinen.
Tested with pkcs11_tool -m ECDH1-DERIVE
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
ref: https://github.com/OP-TEE/optee_os/pull/5130
> libckteec: add support for ECDH derive

- tee-supplicant/src/plugin.c
- tee-supplicant/src/tee_supp_fs.c
- tee-supplicant/src/tee_supplicant.c
- tee-supplicant/src/tee_supplicant.h
Add support to define tee supplicant paths at the run time using env variables.
`OP_TEE_FS_PARENT_PATH`, `OP_TEE_LIB`, and `OP_TEE_PLUGIN_LOAD_PATH`
When trying to run tee supplicant process in confinement, some critical directories needs to be defined dynamically during runtime, rather than at the build time.
This PR enables this run time scenario.
> More env support

- tee-supplicant/src/rpmb.c
- tee-supplicant/src/tee_supplicant.c
- tee-supplicant/src/tee_supplicant.h
In OP-TEE OS, the RPMB device used for secure storage is selected at
compile time via an integer identifier (CFG_RPMB_FS_DEV_ID). As
mentioned in [1], this ID is assigned by the Linux kernel and is used
when tee-supplicant opens the device on behalf of OP-TEE. There are a
couple of issues with that:
1. U-Boot and Linux may assign a different number to the same RPMB
device. Therefore, the TEE supplicant components in U-Boot and Linux
cannot both trust the ID given by OP-TEE.
2. If a system has several RPMB devices, and even if we ignore removable
ones, there is no guarantee that the devices will always be enumerated
in the same order by the kernel on boot. This results in different
device numbers. I observed this behavior on a Hikey620 board with an
external eMMC module plugged into the …
> tee-supplicant: add --rpmb-cid command line option

- tee-supplicant/src/tee_supplicant.c
Commit 5a69d55d6596 ("tee-supplicant: add --rpmb-cid command line option")
mentions in the help string that -r is synonymous for --rpmb-cid, but
it's not. Add the missing characters to the getopt_long() optstring
argument.
> tee-supplicant: accept -r as a short option for --rpmb-cid

- public/tee_client_api.h
Replace TEEC_PARAMS_TYPE with TEEC_PARAM_TYPES.
Signed-off-by: Ding Tao <miyatsu@qq.com>
> public: Fix simple typo in tee_client_api.h

- tee-supplicant/src/tee_supplicant.c
Fix the following build failure with `CFG_TEE_SUPP_PLUGINS != y r`aised since version 3.17.0 and commit [1].
```
/home/giuliobenetti/autobuild/run/instance-2/output-1/build/optee-client-3.17.0/tee-supplicant/src/tee_supplicant.c:104:22: error: 'TEE_PLUGIN_LOAD_PATH' undeclared here (not in a function); did you mean 'TEEC_LOAD_PATH'?
104 |  .plugin_load_path = TEE_PLUGIN_LOAD_PATH,
|                      ^~~~~~~~~~~~~~~~~~~~
|                      TEEC_LOAD_PATH
```
Link: [1] https://github.com/OP-TEE/optee_client/commit/876b1ae719e12890ddd96e85cd4e9862dab46448
Fixes: http://autobuild.buildroot.org/results/384e0ca894dbc0ec72cea76141de890f1ce484db
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
Signed-off-by: Fabrice …
> tee-supplicant/src/tee_supplicant.c: fix build without plugins

- tee-supplicant/src/tee_supplicant.c
The resources of a shm is released in process_free(), this includes the
file descriptor and the memory buffer which was registered. Closing
the file descriptor unregisters the memory buffer.
The memory buffer was, prior to this patch, freed before the file
descriptor was closed. This could lead to another thread reusing this
memory buffer before it has been unregistered. This is normally not a
problem since the buffer will not be read or modified after it has been
freed. However, FF-A mandates that a physical memory isn't registered
already when registering. Son in the case we can have occasional failures.
Fixes: 075c56eebdc9 ("tee_supplicant: add register memory feature")
> tee-supplicant: close shm fd before freeing memory

- config.mk
- tee-supplicant/CMakeLists.txt
- tee-supplicant/src/tee_supplicant.c
- tee-supplicant/src/teec_ta_load.c
- tee-supplicant/src/teec_ta_load.h
Parse CFG_TEE_CLIENT_LOAD_PATH (TEEC_LOAD_PATH) and TEEC_TEST_LOAD_PATH
as a colon-separated list of paths. This commit also updates the
documentation of CFG_TEE_CLIENT_LOAD_PATH and try_load_secure_module()
which were either lacking or incorrect.
Suggested-by: Chao Chen <ccha@amazon.com>
> tee-supplicant: support multiple TA load paths

- libteec/CMakeLists.txt
- tee-supplicant/CMakeLists.txt
CFG_TEE_CLIENT_LOG_LEVEL and CFG_TEE_SUPP_LOG_LEVEL have no effect on
DEBUGLEVEL_X when compiling with cmake.
Therefore, modifying the values of CFG_TEE_CLIENT_LOG_LEVEL and
CFG_TEE_SUPP_LOG_LEVEL cannot set the log level.
Signed-off-by: Lejia Zhang zhanlej@gmail.com
> cmake: fix log level don't take effect

- tee-supplicant/tee_supplicant_android.mk
At the moment the RPMB_EMU variable in the Makefile uses a simple assignment and unconditionally sets the variable.
Move it to a conditional assignment and allow users to override it.
> tee-supplicant: android: make RPMB_EMU a conditional assignment

- libteec/src/teec_benchmark.c
Fixed libteec function mmap_paddr mmap() size problem reported in [1].
Link: [1] https://github.com/OP-TEE/optee_client/issues/318
Signed-off-by: Yuelei Kan <936115299@qq.com>
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
> libteec: fix memory mapping function in benchmark

- tee-supplicant/src/tee_supp_fs.c
A string is empty when its first character is zero. Therefore, we can avoid calling strlen() on each FS request.
> tee-supplicant: fs: no need to use strlen() to check for empty string

- libteeacl/include/teeacl.h
The `uuid` pkg-config file provides the include directory as `${PREFIX}/include/uuid`. Set include path relative to pkg-config file specified include_dir to remain portable.
Signed-off-by: Eero Aaltonen <eero.aaltonen@vaisala.com>
Should fix issue #329
> teeacl: fix include path

- tee-supplicant/src/tee_supp_fs.c
In order to properly syncronize data for secure storage, fsync must be performed on the containing directory after create, mkdir and rename operations.
This may be especially of interest in a production environment where power may be cut as soon as all the security parameters are saved.
Signed-off-by: Joakim Nordell <joakim.nordell@axis.com>
> tee-supplicant: Fix atomic operations for secure storage

- libteec/CMakeLists.txt
- libteec/libteec.pc.in
Autotools build environments that use libteec would benefit from the addition of generated package config files so that libraries could be found wherever they are installed.  Add a teec pkg-config generation to support that
Signed-off-by: Neil Horman <nhorman@gmail.com>
> Add pkgconfig file for libteec

- .github/workflows/ci.yml
- ci/Dockerfile.debian
- ci/Dockerfile.ubuntu
Adds a CI script to be run on push and pull requests. Eight cross-builds are checked: (armhf, aarch64) x (make, cmake) x (x86 Debian, x86 Ubuntu).
> ci: add GitHub Actions script and Docker files

- Makefile
- libteeacl/Makefile
For cross building, the cross version <CROSS_COMPILE>pkg-config should
be used instead of the native pkg-config.
This is because for the dynamic linking dependency such as
uuid-dev/libuuid, the build machine architecture version should not be
used, instead, the host machine version should be used. Or in other
words, install uuid-dev:arm64 for cross building the aarch64 target on
Debian/Ubuntu.
However, the native pkg-config could not find the correct cross
compiling dependencies if only the target arch uuid-dev is installed.
Even worse, it produces the incorrect LFLAGS without the required -L, if
the native uuid-dev is installed.
By adding multiarch, on Debian/Ubuntu, a <CROSS_COMPILE>pkg-config is
created to correctly handle such problem.
This fixes below issues while cross building.
- …
> fix `ld: cannot find -luuid` for cross building

- Makefile
Use `sbindir`, `libdir` and `includedir` as variables for installation targets.
These variables names are defined by GNU coding standards [1].
Link: [1] https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
Signed-off-by: Clement Faure <clement.faure@nxp.com>
> Makefile: use GNU standards for directory variables

- CMakeLists.txt
- flags.mk
- libteeacl/src/group.c
Build failure in http://autobuild.buildroot.net/results/9bda046c3af43765edbc27e2e3c9b6d4a635eef7 (issue #339) seems to be due to uClibc not implementing `reallocarray`. Use `realloc` instead and make the reason explicit.
Also included fix for making compile options clang friendly
> Fix uClibc reallocarray compilation failure and also clang compilation

- libteec/src/tee_client_api.c
When allocating a page aligned buffer, round the size up the next multiple of page size. With this we can guarantee that a part of that page isn't registered already.
> teec: use multiple of page size for page aligned buffers

- Android.mk
- config.mk
- tee-supplicant/CMakeLists.txt
- tee-supplicant/Makefile
- tee-supplicant/src/tee_supplicant.c
- tee-supplicant/src/teec_ta_load.c
- tee-supplicant/tee_supplicant_android.mk
Cleanup TEEC_TEST_LOAD_PATH and CFG_TA_TEST_PATH, as the TEEC_TEST_LOAD_PATH was not working properly anyway.
> tee-supplicant: Cleanup TEEC_TEST_LOAD_PATH

- libckteec/src/serialize_ck.c
This PR adds `serialize_mecha_aes_gcm()` function to `serialize_ck.c` to support AES-GCM mechanism (`CKM_AES_GCM`) in libckteec.
> libckteec: serialize_ck.c: serialize AES-GCM mechanism parameters

- tee-supplicant/CMakeLists.txt
- tee-supplicant/Makefile
- tee-supplicant/tee_supplicant_android.mk
Commit 3ac968ee7c927271e83ea3a4247839649202ab5e moved `linux/tee.h` from `libteec/include` to `libteec/src` resulting in the following build failure with any kernel < 4.16 (i.e before https://github.com/torvalds/linux/commit/033ddf12bcf5326b93bd604f50a7474a434a35f9):
```
/home/buildroot/autobuild/instance-3/output-1/build/optee-client-4.0.0/tee-supplicant/src/tee_supplicant.c: In function 'register_local_shm': /home/buildroot/autobuild/instance-3/output-1/build/optee-client-4.0.0/tee-supplicant/src/tee_supplicant.c:356:44: error: storage size of 'data' isn't known
356 |         struct tee_ioctl_shm_register_data data;
|                                            ^~~~
```
To fix this build failure, update `CMakeLists.txt` and `Makefile` of tee-supplicant to add `libteec/src` to the include …
> tee-supplicant: fix build with kernel < 4.16

- libckteec/src/pkcs11_token.c
When running in 64 bit CPU things like `ulMaxSessionCount` would get value of `4294967295` instead of `~0`.
This fixes problem with https://github.com/latchset/pkcs11-provider usage.
Related issue in `pkcs11-provider` project:
https://github.com/latchset/pkcs11-provider/issues/312
Test case for this:
https://github.com/OP-TEE/optee_test/pull/718
> libckteec: Fix CK_ULONG conversions in C_GetTokenInfo()

- libteec/src/tee_client_api.c
The variable aligned_sz will be 0 when the requested sz is MAX_SIZE. Since posix_memalign can return a valid pointer for zero size allocations, share memory registration requests for MAX_SIZE might make it to the kernel.
This PR stops it early - just as it was before "teec: use multiple of page size for page aligned buffers" was merged.
Fixes: acb0885c117e73cb6c5c9b1dd9054cb3f93507ee ("teec: use multiple of page size for page aligned buffers")
> teec: do fail on MAX_SIZE allocation requests

- libckteec/src/pkcs11_processing.c
Change the one shot encryption and decryption handler function to allow input buffer reference to be NULL. This may happen for example with AES GCM operation where encryption of a NULL buffer is expected to produce an AES GCM authentication tag. Before this change, providing a NULL buffer to C_Encrypt() made ckteec_register_shm() to fail and ckteec_register_shm() to return CKR_HOST_MEMORY error code.
Fixes: aa3dd58d605e ("libckteec: Allow 0 length input buffer  for update operations;")
> libckteec: one shot encryption/decryption may have no input data

- tee-supplicant/src/tee_supplicant.c
In this PR , it fixes bug mentioned in #374.
fixes #374
> tee-supplicant: Fix crash when TA isn't found.

- tee-supplicant/src/rpmb.c
Since commit 37975f1ba31e ("rmpb: update AOSP RPMB device path") the RPMB device patch is the same __ANDROID__ directive being set or not hence simplify the implementation by removing use of that directive.
> tee-supplicant: remove useless use of __ANDROID__ condition

- Android.bp
Fixes the following link error:
```
ld.lld: error: undefined symbol: sd_notify_ready
>>> referenced by tee_supplicant.c:928 (vendor/linaro/optee_client/tee-supplicant/src/tee_supplicant.c:928)
```
Fixes: a5b1ffc ("tee-supplicant: send READY=1 notification to systemd")
> tee-supplicant: add sd_notify.c to Android.bp sources

- libckteec/src/serialize_ck.c
Add `release_serial_object(obj2)` to release obj2 
before `serialize_indirect_attribute()` returns to
prevent memory leakage.
> Fix Memory Leak in serialize_indirect_attribute()

- config.mk
- libteec/CMakeLists.txt
- tee-supplicant/CMakeLists.txt
- tee-supplicant/optee-udev.rules.in
- tee-supplicant/tee-supplicant@.service.in
tee-supplicant startup with systemd init based
is non-trivial. Add needed udev rule and systemd
service files here so that distros can co-operate maintaining them.
Files are from meta-arm https://git.yoctoproject.org/meta-arm at commit 7cce43e632daa8650f683ac726f9124681b302a4 with license MIT and authors:
Peter Griffin <peter.griffin@linaro.org>
Joshua Watt <JPEWhacker@gmail.com>
Javier Tia <javier.tia@linaro.org>
Mikko Rapeli <mikko.rapeli@linaro.org>
The udev rule starts tee-supplicant once optee has been detected via /dev/teepriv[0-9]* device file. The startup expects to find teeclnt system group on the running host. systemd service starts before tpm2.target (new in systemd 256) which starts in initramfs too. This covers firmware TPM TA usecases, and possibly others which are started …
> tee-supplicant: add udev rule and systemd service file

- .devcontainer/Dockerfile.vscode
- .devcontainer/devcontainer.json
- .vscode/extensions.json
This will enable seamless Development of optee_client Project with VSCode
inside Docker container.
The VSCode Container provides:
* Automatic Mapping of the host user UID/GID inside the container
* Cross-Compilers (aarch64/armhf)
* GDB Multiarch for Debugging 
* Remote SSH on the Target with seamless ssh mapping of the Host inside the container (Linux/Windows WSL)
* Git and Git Extensions to work and send Patches
Note: This require Docker installation for Linux/or Windows :
[1] https://docs.docker.com/engine/install
VSCode Extensions (extensions.json) will be recommended for the installation
For more Information :
[2] https://code.visualstudio.com/docs/devcontainers/containers
[3] https://www.youtube.com/watch?v=C_5tDWsWSj0
[4] https://www.youtube.com/watch?v=b1RavPr_878
>  VSCode : Enable Development inside Docker Container

- libckteec/src/serialize_ck.c
I run into an segmentation fault when using following command:
`$ pkcs11-tool --module /usr/lib/libckteec.so.0 --login --sign -m EDDSA --slot 0 --id 01 --input-file /tmp/data --output-file /tmp/data.sig`
After bit of digging I found out that there is no parameterLen validation in EdDSA mechanism branch which result in null pointer dereference.
This fixes Segmentation fault when no parameter is provided as specified in pkcs11 v3.0 spec for Ed25519 Signature Scheme
> Validate EdDSA mechanism parameter length

- CMakeLists.txt
[CMake 4.0 was released](https://www.kitware.com/cmake-4-0-0-available-for-download/) which dropped compatibility with versions older than 3.5.
Bump the minimum required version to 3.5, which was released 9 years ago.
> cmake: raise mimimum required to 3.5

- tee-supplicant/src/tee_supp_fs.c
The TEE_FS_FILENAME_MAX_LENGTH is not used anywhere so remove it.
> tee-supplicant: remove unused TEE_FS_FILENAME_MAX_LENGTH
